# Sample file for using docker-compose with the ManiaPlanet Dockerfile.
services:
  dedicated:
    image: dedicated
    build: .
    restart: unless-stopped
    env_file: ./dedicated_vars.default.env
    volumes:
      - ./UserData:/app/dedicated/UserData
      - ./Logs:/app/dedicated/Logs
    ports:
      - 5000:5000
      - 2350:2350
      - "2350:2350/udp"
      - "3450:3450"
      - "3450:3450/udp"